codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 50..100
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "desktop/build.rs"
  - "desktop/gen/**"
  - "src/**/*.test.js"
